version: "3.5"

services:
  nginx:
    depends_on:
      - stock
      - amazingchat
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
    networks:
     - amazing-dev

  db:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: MyPass@word
    volumes:
      - ./dbdata:/var/opt/mssql/data
    ports:
      - "1433:1433"
    restart: always
    networks:
     - amazing-dev

  rabbitmq:
    image: rabbitmq:management
    hostname: "messageBroker"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 15s
      retries: 3
    networks:
      - amazing-dev
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "PASSWORD" 

  stock:
    depends_on:
      - rabbitmq
    environment:
      - RabbitMQSettings__ConnectionString=amqp://rabbitmq:PASSWORD@rabbitmq:5672
      - ConnectionStrings__DefaultConnection=Data Source=db,1433;Initial Catalog=AmazingChatDb;User Id=sa;Password=MyPass@word;Trusted_Connection=False;MultipleActiveResultSets=true
    build:
      dockerfile: ./AmazingChat.StockBot/Dockerfile
    restart: always
    networks:
            - amazing-dev

  amazingchat:
    depends_on:
     - rabbitmq
     - stock
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=db,1433;Initial Catalog=AmazingChatDb;User Id=sa;Password=MyPass@word;Trusted_Connection=False;MultipleActiveResultSets=true
      - ConnectionStrings__IdentityConnection=Data Source=db,1433;Initial Catalog=AmazingChatIdentityDb;User Id=sa;Password=MyPass@word;Trusted_Connection=False;MultipleActiveResultSets=true
      - RabbitMQSettings__ConnectionString=amqp://rabbitmq:PASSWORD@rabbitmq:5672
      - SignalR__UrlStockBot=http://stock/api/
    build:
      dockerfile: AmazingChat.UI/Dockerfile
    restart: always   
    networks:
            - amazing-dev

volumes:
  dbdata:  
  rabbit:

networks:
    amazing-dev: